### ISSUE TITLE
Figure G.2.25 Picture Essence Coding does not agree with text

### ISSUE THREAD

**Issue by mrmxf** [SMPTE/ST377-1-full-revision#17]
Created by Lars Borg during Constrained review of ST377-1:2011 FCD Ballot
For UL: **`06.0E.2B.3404.01.01.0A04.01.02.0101.02.02.01`**, the text and figure for Interleaved, 4:2:2, 10-bit component seem out of sync.

- Text says Cr, Y, Cb, Y
- Figure shows Cb Y Cr Y

Is the datum order reversed for this item? Or is the figure wrong?

**Comment by TatsujiYamazaki** [comment]
same as https://github.com/SMPTE/ST377-1-full-revision/issues/10

**Comment by mrmxf** [comment]
copying text to #10 and closing this issue
